# Generated by Django 5.1.5 on 2025-01-25 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquiries",
            old_name="data",
            new_name="date",
        ),
    ]
