# Generated by Django 5.1.5 on 2025-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0002_rename_data_inquiries_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="brokerage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
