# Generated by Django 5.1.1 on 2025-01-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0004_alter_apartment_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiries",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.apartment"
            ),
        ),
    ]
